mv db.json db.json.bak

npm run start -- player add "Abe Binder"
npm run start -- player add "Brandon Tartar"
npm run start -- player add "Daniel Liam"
npm run start -- player add "David Yang"
npm run start -- player add "Hogan Hsu"
npm run start -- player add "Jake Mann"
npm run start -- player add "Joshua Moutry"
npm run start -- player add "Kyle Kowalski"
npm run start -- player add "Nick Harder"
npm run start -- player add "Reid Backstrom"
npm run start -- player add "Teoh Zheyi"
npm run start -- player add "Victoria Kowalski"

npm run start -- session create "2025-04-18"
npm run start -- session add-player "2025-04-18" "Abe Binder"
npm run start -- session add-player "2025-04-18" "Brandon Tartar"
npm run start -- session add-player "2025-04-18" "Daniel Liam"
npm run start -- session add-player "2025-04-18" "David Yang"
npm run start -- session add-player "2025-04-18" "Hogan Hsu"
npm run start -- session add-player "2025-04-18" "Jake Mann"
npm run start -- session add-player "2025-04-18" "Joshua Moutry"
npm run start -- session add-player "2025-04-18" "Kyle Kowalski"
npm run start -- session add-player "2025-04-18" "Nick Harder"
npm run start -- session add-player "2025-04-18" "Reid Backstrom"
npm run start -- session add-player "2025-04-18" "Teoh Zheyi"
npm run start -- session add-player "2025-04-18" "Victoria Kowalski"

npm run start -- session generate-rounds "2025-04-18"